### ISSUE TITLE
PurPur 1.18.1 - java.lang.ClassNotFoundException: me.wiefferink.areashop.nms.v1_18_R1.NMSImpl

### ISSUE THREAD

**Issue by TomLewis** [md5sha256/AreaShop#4]
**Current behaviour**

Ahoy, currently does not boot on PurPur 1.18.1.

```
[09:55:49] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.7.0-SNAPSHOT
[09:55:49] [Server thread/WARN]: java.lang.ClassNotFoundException: me.wiefferink.areashop.nms.v1_18_R1.NMSImpl
[09:55:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[09:55:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[09:55:49] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[09:55:49] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[09:55:49] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[09:55:49] [Server thread/WARN]: 	at AreaShop-2.7.0-SNAPSHOT.jar//me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:177)
[09:55:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:55:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:55:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:55:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[09:55:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[09:55:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732)
[09:55:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508)
[09:55:49] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349)
[09:55:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
[09:55:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[09:55:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[09:55:49] [Server thread/ERROR]: [AreaShop] Failed to initialize NMS implementation!
[09:55:49] [Server thread/INFO]: [AreaShop] Disabling AreaShop v2.7.0-SNAPSHOT
```

**Your environment**
* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: AreaShop-2.7.0-SNAPSHOT.
* WorldEdit version: FastAsyncWorldEdit version 2.0.0-SNAPSHOT-57;64442a8
* WorldGuard version: WorldGuard version 7.0.6+1cff55f
* Vault version: Vault version 1.7.3-b131

**Comment by md5sha256** [comment]
Wrong jar used.
