### ISSUE TITLE
Unknown WE Version: 2.0.0-SNAPSHOT-57;64442a8

### ISSUE THREAD

**Issue by TomLewis** [md5sha256/AreaShop#5]
**Current behavior**

Most likely because i'm using FAWE, when you go to download it, hes got another 2.0 build for 1.18;
https://ci.athion.net/view/%20%20FastAsyncWorldEdit/job/FastAsyncWorldEdit/

```
[22:10:35] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.7.1
[22:10:35] [Server thread/ERROR]: Error occurred while enabling AreaShop v2.7.1 (Is it up to date?)
java.lang.IllegalStateException: Unknown WE Version: 2.0.0-SNAPSHOT-57;64442a8
	at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:210) ~[AreaShop-2.7.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[purpur-1.18.1.jar:git-Purpur-1497]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[purpur-1.18.1.jar:git-Purpur-1497]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732) ~[purpur-1.18.1.jar:git-Purpur-1497]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) ~[purpur-1.18.1.jar:git-Purpur-1497]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:349) ~[purpur-1.18.1.jar:git-Purpur-1497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1497]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1497]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:10:35] [Server thread/INFO]: [AreaShop] Disabling AreaShop v2.7.1
```

**Your environment**
* Server platform (Bukkit, Spigot, etc.): PurPur
* Server version: PurPur 1.18.1
* AreaShop version: AreaShop-2.7.2.jar
* WorldEdit version: FAWE  2.0.0-SNAPSHOT-57;64442a8
* WorldGuard version: 7.0.6
* Vault version: 1.7.3-b131

**Comment by md5sha256** [comment]
Resolved in [b3f1225](https://github.com/md5sha256/AreaShop/commit/b3f1225934df9a3fac611fc5f916f7479e82c242). Thanks for reporting
